# fly.toml app configuration file generated for number-place-player on 2024-12-19T11:51:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'number-place-player'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
